#!/system/bin/sh

sendevent /dev/input/event3 3 24 13; sendevent /dev/input/event3 1 330 1; sendevent /dev/input/event3 3 48 13; sendevent /dev/input/event3 3 53 $1; sendevent /dev/input/event3 3 54 $2; sendevent /dev/input/event3 3 57 0; sendevent /dev/input/event3 0 2 0; sendevent /dev/input/event3 0 0 0
